package org.myorg.myorg;

// Generated by GraphWalker (http://www.graphwalker.org)
import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "final.json")
public interface CitySearchDemo {

    @Vertex()
    void v_ShowAllSearch();

    @Vertex()
    void v_ValidCityEntered();

    @Edge()
    void e_EnterCity();

    @Edge()
    void e_ClickInfoSearchButton();

    @Edge()
    void e_goBackWeather();

    @Edge()
    void e_invalidCity();

    @Edge()
    void e_init();

    @Edge()
    void e_ClickShowAllButton();

    @Edge()
    void e_ClickCurrency();

    @Vertex()
    void v_CurrencySearch();

    @Edge()
    void e_ClickWeatherButton();

    @Vertex()
    void v_WeatherSearch();

    @Vertex()
    void v_SiteIdle();

    @Edge()
    void e_goBackShowAll();

    @Edge()
    void e_goBackCurrency();

    @Edge()
    void e_goBackInfo();

    @Vertex()
    void v_InfoSearch();
}
