package org.myorg.myorg;

// Generated by GraphWalker (http://www.graphwalker.org)
import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "template.json")
public interface CitySearchDemo {

    @Vertex()
    void v_ShowAllSearch();

    @Vertex()
    void v_ValidCityEntered();

    @Edge()
    void e_invalidCity();

    @Edge()
    void e_init();

    @Vertex()
    void v_CurrencySearch();

    @Vertex()
    void v_WeatherSearch();

    @Vertex()
    void v_SiteIdle();

    @Edge()
    void e_goBackShowAll();

    @Vertex()
    void v_InfoSearch();

    @Edge()
    void button_currencyReturn();

    @Edge()
    void button_showInfo();

    @Edge()
    void button_showAll();

    @Edge()
    void button_infoReturn();

    @Edge()
    void button_weatherReturn();

    @Edge()
    void button_showCurrency();

    @Edge()
    void button_showWeather();

    @Edge()
    void text_searchInput();
}
