package org.myorg.myorg;

// Generated by GraphWalker (http://www.graphwalker.org)
import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "template.json")
public interface TestShop {

    @Vertex()
    void v_ProductClicked();

    @Vertex()
    void v_signInPage();

    @Edge()
    void css_buttondotbuttondotbtn();

    @Vertex()
    void v_HomePage();

    @Edge()
    void css_buttondotexclusive();

    @Edge()
    void text_email();

    @Edge()
    void css_imgdotreplacemns2xdotimgmnsresponsive();

    @Vertex()
    void v_ProductAddedToCart();

    @Vertex()
    void v_GoToCart();

    @Vertex()
    void v_ClickCheckOut();

    @Edge()
    void css_spandotajaxczgcartczgproductczgtxt();

    @Vertex()
    void v_VerifyAddress();

    @Vertex()
    void v_passwordEntered();

    @Edge()
    void css_selectdotformmnscontrol();

    @Vertex()
    void v_PaymentDone();

    @Vertex()
    void v_loggedIn();

    @Edge()
    void css_adotlogin();

    @Edge()
    void text_passwd();

    @Vertex()
    void v_SizeSelected();

    @Edge()
    void css_adotsfmnswithmnsul();

    @Edge()
    void name_processAddress();

    @Vertex()
    void v_emailEntered();

    @Vertex()
    void v_VerifyCarrier();

    @Edge()
    void e_init();

    @Edge()
    void css_dotstandardmnscheckoutdotbuttonmnsmedium();

    @Vertex()
    void v_GoToMainPage();

    @Vertex()
    void v_CheckboxClicked();

    @Vertex()
    void v_WomanSection();

    @Edge()
    void button_SubmitLogin();

    @Edge()
    void id_cgv();

    @Vertex()
    void v_initiated();

    @Vertex()
    void v_PaymentMethodSelected();

    @Edge()
    void name_processCarrier();

    @Edge()
    void css_adotbankwire();
}
